language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github_token: $github_token
  target-branch: gh-pages
  local_dir: build
  on:
    branch: master
